### ISSUE TITLE
无法去除SwiftUI 中 List 默认的横线和默认的外边距间距，和默认背景

### ISSUE THREAD

**Issue by pengzhenkun** [GarveyCalvin/SwiftUI-Tutorials#1]
无法去除SwiftUI 中 List 默认的横线和默认的外边距间距，和默认背景，已经下载你的Demo，跑起来的效果也不行，希望跟进看一下

**Comment by 810152690** [comment]
是的，我这边默认的横线还是存在，有其他方法嘛

**Comment by GarveyCalvin** [comment]
@pengzhenkun @810152690 我对此很感兴趣，我在 iOS15 系统上解决了这三个问题：
1. 默认的横线
2. 默认的边距
3. 默认的背景
注意：因为隐藏横线的 API 在15上才提供，并且我实测是在 iOS17.0.2 系统
请你们 pull 最新的代码运行查看，感谢提 issue。
